server:
  port: 5005
spring:
  application:
    name: booking-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/booking_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/